### ISSUE TITLE
Improve README

### ISSUE THREAD

**Issue by deepak2431** [opencollective/documentation-old#16]
I would request the following  improvements that can be done in the README:
1. Addition of logo of open collective organization.
2. Addition of link of the slack channel.
3. Adding the guidelines to create how to create a pull request.
4. Addition of contribution guidelines.
5. Structuring the whole readme in different sections as about, communication means, contribution and pull request guidelines.
5. Removing the FAQ section from the README and adding it as separate section in the documentation page.

Further improvements and changes can be done after review from the community members.

Thanks!
Deepak Kumar

**Comment by jaskiratsingh2000** [comment]
Hi @deepak2431 thanks for reaching out. I am yet kinda confused that where exactly are you referring to because this docum3ntation contains everything you proposed as of now but I am not sure that where exactly you are proposing.
Can you elaborate more ?

Thanks

**Comment by deepak2431** [comment]
Hi @jaskirat2000,
Thanks for reviewing. I am proposing the changes to the Readme present over here https://github.com/opencollective/documentation

Thanks!
