### ISSUE TITLE
Updating references to external content

### ISSUE THREAD

**Issue by contraexemplo** [opencollective/documentation-old#40]
Our docs have few references to external documentation, but they are all pretty significant: they are either essays written by core contributors, or messages of support and approval from members. In special, since it our docs were first written, Open Collective has abandoned Medium and moved its blog to Ghost. Referencing the right links to the right content here is relevant to those who will discover this kind of content and wish to follow a RSS feed or subscribe to the newsletter. I believe we should update them accordingly.

**Comment by contraexemplo** [comment]
@alanna I created an issue to expand on that question I asked on Slack. :blush:

**Comment by alanna** [comment]
Great! Yes it would be best to update links to the new URLs. We left the old content on Medium but each has been copied to the OC blog and that's the main content location now.

**Comment by contraexemplo** [comment]
@Alanna what do you think about getting a few new tweets of people talking about OC as well?

**Comment by alanna** [comment]
@contraexemplo new tweets would be cool! We have tweets in every newsletter so I would start by looking there for recent examples.

**Comment by contraexemplo** [comment]
Just found out that embedding tweets with GitBook is... not a good experience. When I get the code to embed it, they just convert it to plain text. Should I transform those into images or should I embed them like that, @alanna? See https://docs.opencollective.com/help/financial-contributors/organizations/sustainer-resources for two examples of how it embeds tweets.

**Comment by alanna** [comment]
It's not super pretty how they are embedded, but I think it's OK as long as
people can see the basic info. It's better than images because it has links
included. There are newer tweets in each monthly newsletter so you could
update that page with more recent examples.

**Comment by contraexemplo** [comment]
FYI, Twitter's new code for embedding content is not supported by GitBook yet. If your desktop UI was updated to the new one (which is similar to their mobile website), embedding tweets won't work. The code block they used to offer on the old UI, however, is still accepted by GitBook.

To revert to the old UI, you will have to use an add-on called [GoodTwitter](https://github.com/ZusorCode/GoodTwitter). It is available on both Firefox and Chrome. (I'm going to add this to the **Suggesting changes** page.)
