### ISSUE TITLE
GitBook's own version control: yay or nay?

### ISSUE THREAD

**Issue by contraexemplo** [opencollective/documentation-old#41]
I merged the new organization again and GitBook didn't render it right *again* (don't worry, I reverted the merge!). So I have a new idea:

GitBook offers the following feature:
- We can sync as many branches as we want from GitHub
- We are also able to transform them into versions (doc version 1.0.0, etc) publicly accessible to anyone or delete a whole deprecated version easily

My [meta GitBook](https://documentarians.gitbook.io/metadocumentation/ ) showcases this. I set up the `open-collective`branch (https://github.com/contraexemplo/metadocumentation/tree/open-collective) as the main docs/most current documentation and there's a link to the `redirect` branch (https://github.com/contraexemplo/metadocumentation/tree/redirect) with the old version of said documentation. We could do the same for the new organization while keeping the old version live as well.

**Comment by contraexemplo** [comment]
cc: @jaskirat2000 and @alanna

**Comment by contraexemplo** [comment]
Follow up after the meeting I had with @alanna: I will try this tomorrow and see how it goes. We agreed that we are at a point of the project that moving on to other tasks will be more beneficial to the docs. We also agreed that talking to the developers about developing a strategy to document new versions of the app is much needed—and if we choose to stick with GitBook in the end, this feature may be handy.

Tasks for tomorrow:
- [x] Check the [Releases](https://docs.gitbook.com/content-editing/releases) functionality page again to identify the best strategy for our documentation
- [x] Perform some tests on my test GitBook
- [x] Stage changes through GitBook
- [x] Evaluation: did it work as expected?
- [x] Write a blog post about all of this!

**Comment by contraexemplo** [comment]
@alanna I was able to successfully import and render the new organization using the Release functionality: https://docs.opencollective.com/help/v/v2/

**Comment by alanna** [comment]
Great! It looks good. So is the plan to continue editing the V2 release and then migrate it to be the main docs by the end of the project?

**Comment by contraexemplo** [comment]
@Alanna Yes, we would mark it as the main branch and it would take the place from the current documentation.

**Comment by contraexemplo** [comment]
v2 is now the default docs for everyone on GitBook but I need to make a change here to make that branch the main one here. @alanna I don't have the access permissions to do this, would you be able to make that change?

**Comment by alanna** [comment]
I'm not sure how to do that, @contraexemplo - I think I succeeded in making you an admin of this repo just now so can you try again? If you need me to do it let me know how.

**Comment by contraexemplo** [comment]
Thanks @alanna! `v2` is now the main branch on GitBook and GitHub. :tada:

**Comment by alanna** [comment]
@contraexemplo can you change "V2" to something more descriptive like "help" or "docs" so it shows up here?

<img width="1268" alt="Screen Shot 2019-11-08 at 1 15 11 PM" src="https://user-images.githubusercontent.com/5498878/68438738-fecd3f00-0229-11ea-8ecc-df37217776d4.png">
