### ISSUE TITLE
Broken images links

### ISSUE THREAD

**Issue by Betree** [opencollective/documentation-old#44]
There are broken images in the documentation, see https://docs.opencollective.com/help/financial-contributors/organizations/gift-cards#faq for example.

Problem seems to come from https://github.com/opencollective/documentation/commit/a3ece2d7529435da80200ecf2162f5d4c3461afc#diff-0453d5dcc4be328ac7fe8a9c43ba2a4c. Git seems to say I've made some of these changes, but I haven't renamed these files.

@contraexemplo any idea of what could be the reason?

**Comment by contraexemplo** [comment]
This is a problem I'm aware of and I'm slowly solving as I review the content of every page. Design docs had a similar issue, every image was broken for some reason. I didn't find a pattern that would help me understand why a few images broke while others didn't; it seems to be pretty random, actually. Maybe it was a change on how they handle images? They changed a few things internally this month (see https://blog.gitbook.com/changelog).

It's a really slow issue to solve as they don't link images directly from our repository, I have to double check the raw content to see the names of all broken images to restore them through GitBook's interface. You can follow my progress here: https://gist.github.com/contraexemplo/96a08878f498a7c49b118f18c8ffc8e4

I've found that following changes through Git isn't reliable at all. They state in their documentation that Git serves just as a mirror; the versioning system they use internally was designed by them. One thing that happened to me earlier this week was that GitBook restored some images I deleted and created copies of some I repeatedly used in the same page. I'm not sure why they did that either. :man_shrugging:

**Comment by contraexemplo** [comment]
- Some broken images don't seem to be located in our repository (see https://raw.githubusercontent.com/opencollective/documentation/v2/collectives/events.md)
- Some can't be found in searches on GitBook's interface (i.e. https://github.com/opencollective/documentation/blob/v2/.gitbook/assets/screen-shot-2019-05-28-at-12.44.15-pm%20(1).png from https://docs.opencollective.com/help/financial-contributors/organizations)
- Some can be found on GitBook's interface but for unknown some reason, they broke (this is what happened to the gifs on the Gift Cards page)

**Comment by contraexemplo** [comment]
I discovered something interesting: some of the broken images had their names modified on GitBook. For instance, `screen-shot-2019-05-23-at-1.01.51-pm.png` was rewritten as `Screen Shot 2019-05-23 at 1.01.51 PM.png`. This happened with both images on https://docs.opencollective.com/help/internal/projects/maintainerati-berlin-2019.
