### ISSUE TITLE
Collective to Collective donations is unclear how to submit expense request from one collective to another

### ISSUE THREAD

**Issue by atodorov** [opencollective/documentation-old#63]
I am in the process of migrating fiscal hosts from US to Europe. From the documentation, nor the UI it is not clear to me how my `kiwitcms-europe` collective should submit an expense report to my `kiwitcms` collective so I can zero the funds for `kiwitcms` and migrate its fiscal host. 

Can you give me an example, I will contribute a pull request to the docs to make this clear.

**Comment by piamancini** [comment]
Hi @atodorov 
You need to get your fiscal host in europe to submit an expense to your collective in the US. 
Then your fiscal host in the US (OSC) will pay that to your new host and you can archive the collective. Your new host can then add the funds to the European collective.
Who's your host in Europe?
We are not ready yet for expenses on behalf of collectives. We will be soon :)

**Comment by atodorov** [comment]
@piamancini the European host is OSC Europe.

edit: to be clear I don't want to archive the old collective b/c we'll lose all of the history. I just need to shuffle the funds through the temporary collective in Europe, then move the existing collective to the European host and shuffle the funds back again.

**Comment by jfdh** [comment]
Hi @piamancini ,
Before submitting this expense, I wonder if I should include euro or dollar currency on the invoice? 
Thanks for your answer,
JF

**Comment by piamancini** [comment]
@jfdh you should make it in USD  - thank you!
