### ISSUE TITLE
Broken links on doc for manual reporting

### ISSUE THREAD

**Issue by whoabuddy** [opencollective/documentation-old#72]
The two links on the [Manual Reporting](https://docs.opencollective.com/help/contributing/development/manual-reporting) page are broken.

The current links from [manual-reporting.md](https://github.com/opencollective/documentation/blob/v2/contributing/development/manual-reporting.md):

- https://github.com/OpenCollective/opencollective-api/blob/master/templates/emails/group.monthlyreport.hbs
- https://github.com/OpenCollective/opencollective-api/blob/master/cron/monthly/email-report.js#L30

It looks like the correct links should be:

- https://github.com/opencollective/opencollective-api/blob/master/templates/emails/collective.monthlyreport.hbs
- https://github.com/opencollective/opencollective-api/blob/master/cron/monthly/collective-report.js

**Comment by Betree** [comment]
Fixed in https://github.com/opencollective/documentation/pull/73
