### ISSUE TITLE
API to extend the information requested to participants

### ISSUE THREAD

**Issue by npettiaux** [opencollective/documentation-old#75]
We use you system a payment collector that produces automagically a accounting report. We need to collect more information about the participants.
We would like to be able, first through your interface, then through an API, theses other characteristics and be able to get them afterwards.
Much thanks

**Comment by Betree** [comment]
Hi @npettiaux, we have a feature in beta-testing that could help to achieve that. Please open an issue on our main repo if you're still looking for that, with details about what kind of info you would like to collect: https://github.com/opencollective/opencollective/issues/new/choose.
