### ISSUE TITLE
Bank account is test account (GitHub Sponsors)

### ISSUE THREAD

**Issue by dtugend** [opencollective/documentation-old#81]
The documentation currently still lists these:
- Routing number: 123205054
- Account Number: 4866342233

However according to Stripe this is a test account that can not be used in live mode:
![image](https://user-images.githubusercontent.com/3610128/88364823-74f7de80-cd84-11ea-888d-e7cb88da50ce.png)

So you might want to check your bank account / account number and I'll probably also have to contact Stripe, because due to that error message I won't also be able to change it to the correct number.

Too bad already 40 USD went there on Jul 22 :S
Edit: (And they didn't arrive in our https://opencollective.com/advancedfx yet, so they might be lost.)

**Comment by piamancini** [comment]
@alanna we need to update this with the new OSC bank account - can you please coordinate with github?

**Comment by alanna** [comment]
I will get this updated in the docs ASAP. Sorry @dtugend - we changed our bank account and forgot to update it here. I'm just confirming the details.

**Comment by alanna** [comment]
@dtugend - I have updated the documentation. The routing number is the same but the account number should be `4869374308`.

I will also contact Github about your past transaction. We should be able to find the funds and get them to the right place.

**Comment by dtugend** [comment]
Thank you very much.
I was able to change the account number to the new one this time (don't know why it worked this time).

Would be awesome if the founds are not lost, but we'll survive if they are as well.
I am personally wondering if this problem might affect others and how to inform them, but I don't know.

**Comment by alanna** [comment]
@dtugend - I'm glad you were able to update it.

I am in touch with Github and I've asked them if all the Collectives need to do anything about the new bank account number (and about your $40). We didn't think about this soon enough but we'll find a solution! Thanks for bringing it up.

I will close this issue now.
